### ISSUE TITLE
FTDI Bitbang on Mac OS X Mountain Lion

### ISSUE THREAD

**Issue by jverkoey** [PaintYourDragon/p9813#1]
Thanks for this awesome library Phil! I've been trying to get it working on Mac OS X Mountain Lion and have found that the make unload/load commands can't find com.FTDI.driver.FTDIUSBSerialDriver. It seems like the demo program runs without needing to disable that so I'm assuming that perhaps I don't need to if com.FTDI.driver.FTDIUSBSerialDriver isn't installed?

Another question: I've noticed that the throughput of the demo app is roughly 17FPS with 3 strands at 512 pixels each. Is this expected throughput?

Thanks again :) Lookin' forward to contributing back to this project!

**Comment by PaintYourDragon** [comment]
Howdy!

Yeah, if you don't have the FTDI "virtual COM port" driver installed, you can ignore that part of the directions.

As for throughput, that looks about right.  If you need better frame rates, I'd suggest more strands in parallel, e.g. 6x256, or 8x192 (if you enable the high speed hardware bitbang thing).

**Comment by jverkoey** [comment]
Cool good to know! I've ordered the ftdi to serial breakout board so that
we can hit higher fps with 6 strands of 256.

Will send updates soon :)

On Nov 24, 2012, at 12:21 PM, Paint Your Dragon notifications@github.com
wrote:

Howdy!

Yeah, if you don't have the FTDI "virtual COM port" driver installed, you
can ignore that part of the directions.

As for throughput, that looks about right. If you need better frame rates,
I'd suggest more strands in parallel, e.g. 6x256, or 8x192 (if you enable
the high speed hardware bitbang thing).

—
Reply to this email directly or view it on
GitHubhttps://github.com/PaintYourDragon/p9813/issues/1#issuecomment-10683250.

**Comment by jverkoey** [comment]
Hallo again! I'm trying to test out the library with a strand of 25 pixels to start and am running into a problem getting it to do anything but make the pixels red.

I have the following wiring setup:

```
FTDI cable:                            TCL
CTS (Brown) -------------------------- Clock (Yellow)
TX (Orange) -------------------------- Data (Green)
GND (Black) ---o---------------------- GND (Blue)
               |    ------------------ +5VDC (Red)
5V 4A PSU      |    |
           GND |    |  +5V 
```

Am I doing something wrong to cause this? I've tried explicitly setting other color values to the strand and it only seems to react to red for some reason.

**Comment by jverkoey** [comment]
What's interesting is that if I unplug the PSU the strand gets even brighter...

**Comment by jverkoey** [comment]
Hah, it's late and I forgot that the outlet that I was plugging the PSU into no longer worked in the workshop >.<

All is well now!
